### ISSUE TITLE
request->getParsedBody() returns null

### ISSUE THREAD

**Issue by aarbrown** [herloct/codeception-slim-module#1]
Hello,

Thank you for writing this library to integrate slim PHP with codeception.  I've found it very handy so far.  That being said, I believe I have found a bug.  When using the codeception-slim-module, the request->getParsedBody() method always returns null.  I believe this is due to the following code in Lib\Connector\Slim.php lines 56-61:

```
$parsed = [];
if ($request->getMethod() !== 'GET') {
    $parsed = $request->getParameters();
}
$slimRequest = $slimRequest
  ->withParsedBody($parsed);
```

My 'fix' for the bug was to remove those lines :) but I'm not sure if I'm breaking some other functionality in doing so.  I'm not sure what the original intention for that code was and I am hoping you can help guide me to a solution for the issue.  I'm working on a test that will illustrate the bug and will submit a pull request referencing this issue.

**Comment by herloct** [comment]
Thanks for the report. I'll review it quickly.
Looks like some strange thing happens when setting `withParsedBody()`.

**Comment by herloct** [comment]
Fixed using your pull request + some editing.

Thanks
