### ISSUE TITLE
use app container to get request, response, etc...

### ISSUE THREAD

**Issue by aarbrown** [herloct/codeception-slim-module#3]
Hello,

I ran into an issue where I was extending the slim response in the container for my app and the test was failing because we are creating new Slim\Http\Response's instead of getting them from the app's container in this module.

I only have a need right now to retrieve the response from the container.  However, I could imagine that anything that's in the container is fair game for extension.  With that in mind, I looked at retrieving the request object from the container but that one seems to be more difficult since we have to inject a mock environment into Slim.  Which brings me to why I'm opening this issue.

Currently, this module expects the user to fully instantiate a Slim app inside a DI container.  This makes it difficult (perhaps impossible) for the module to inject the mock environment into Slim later down the road which, in turn, makes it difficult for us to use the request in the app's container.

Personally, I think the way the container is structured would have to be changed.  Maybe we could require 'middleware' and 'routes' services in the container instead of App::class.  Then we could instantiate the slim app with our mock environment and add the middleware and routes from the container to our app.

Of course, if there's a way to just Slim to parse the mock environment after it's instantiated, that would work too.

I'd like to get your thoughts on how we might be able to get around this.

**Comment by aarbrown** [comment]
Also, I am going to open a PR that has code that uses the response from the app container so you can see more clearly what I'm talking about.

**Comment by herloct** [comment]
Thanks for your suggestion and support.
This module was created by simply copying ZendExpressive's module, so I'm not thinking something that far.
I'll try to review the PR.

**Comment by herloct** [comment]
> Currently, this module expects the user to fully instantiate a Slim app inside a DI container. 

I think current approach is sufficient.
Because we want to test our Slim App as a whole, not as a routes nor middlewares.
If we want to test a middlewares, we could use some unit testing, and freely mock the request and response.

> Then we could instantiate the slim app with our mock environment and add the middleware and routes from the container to our app.

I think we shouldn't mock the environment manually when doing functional/acceptance test, and let Codeception mock it for our test.
