### ISSUE TITLE
Module \Herloct\Codeception\Module\Slim could not be found and loaded

### ISSUE THREAD

**Issue by craicoverflow** [herloct/codeception-slim-module#5]
I have not been able to enabled this module to work with my Slim REST API. I have followed the README.md but it is not very clear and should be expanded.

> [Codeception\Exception\ConfigurationException]
> Module \Herloct\Codeception\Module\Slim could not be found and loaded

Is there any chance you could expand the documentation a bit further as there is no other information online.

Thanks.

**Comment by herloct** [comment]
Ok, i will try it on my local first

**Comment by herloct** [comment]
Here is sample project for my module:
https://github.com/herloct/codeception-slim-module-example

Sorry for the inconvenience.

**Comment by craicoverflow** [comment]
Thanks @herloct I got it working 😄

**Comment by herloct** [comment]
@craicoverflow you're welcome, sorry for the inconvenience :)

I'll close the issue now.
